# Site Settings
locale                   : "en"
name                     : "Kyumin's Website"
title                    :
description              : 
url                      : https://miniprime1.github.io
markdown                 : kramdown

# GitHub
baseurl                  : /
repository               : miniprime1/miniprime1.github.io

# Site Author
author:
  name             : "Kyumin"
  bio              : "Hey, I’m Kyumin [miniprime1] living in South Korea. I am a fan of programming and games. I’m also interested in movies."

# Site Files
include:
  - index.html
exclude:
  - index.md
