# Site Settings
locale                   : "en"
name                     : "Kyumin Nam"
title                    :
description              : 
url                      : https://miniprime1.github.io
markdown                 : kramdown

# GitHub
baseurl                  : /
repository               : miniprime1/miniprime1.github.io

# Site Author
author:
  name             : "Kyumin"
  bio              : "Hello, I'm Kyumin, with miniprime1 (or miniprime) as id. I’m interested in mathematics and programming."

# Site Files
include:
  - index.html
  - /img/favicon.png
exclude:
  - index.md
  - license.txt
  - readme.md
