# Site Settings
locale                   : "en"
title                    :
name                     : "Kyumin's Website"
description              : "Kyumin's Portfolio"
url                      : https://miniprime1.github.io
markdown                 : 1

# GitHub
baseurl                  : /
repository               : miniprime1/miniprime1.github.io

# Site Author
author:
  name             : "Kyumin"
